EntityFramework Tasks
Anvean21/KovalenkoEvgeniy-Homework pull request #18
Opened 2021-06-12 11:41 UTC by Anvean21

2021-06-13 21:50 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.BLL/Services/DirectoryService.cs
> +            var files = fileRepository.GetAsync(specFile,
А почему у тебя гет асинх не возвращает такск?

2021-06-13 21:51 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.BLL/Services/DirectoryService.cs
> +            var directories = directoryRepository.GetAsync(specDir, pageNumber, pageSize, cancellationToken).Result.Items.ToList();
А можно было одним разом всё вытащить

2021-06-13 21:51 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.BLL/Services/FileService.cs
> +        private readonly IRepository<File> fileRepository;
А в идеале должен был получиться один репозиторий. Эх, жаль(

2021-06-13 21:52 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.BLL/Services/FileService.cs
> +            var files = imageFileRepository.GetAsync(imgSpec, cancellationToken).Result.GroupBy(x => x.Type).Select(x => $" {x.Key}, Count = {x.Count()} ")
Хехехе, то есть перед тем чтобы подсчитать ты всё вытягиваешь)
Нет, так не пойдёт это неверно.
Скажу так, можно было было сделать процедуру и дернуть ее

2021-06-13 21:54 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.Core/Interfaces/IRepository.cs
> +        Task<PagedList<TEntity>> GetAsync(Specification<TEntity> specification, int pageNumber, int pageSize, CancellationToken cancellationToken = default);
Тут каких-то методов не хватает.
Я же вроде говорил круд сделать

2021-06-13 21:54 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.Core/Services/IFileService.cs
> +        public Task<PagedList<File>> GetReadFiles(int userId, int directoryId, int pageNumber, int pageSize, CancellationToken cancellationToken = default);
Почему нет суффикса асинх?

2021-06-13 21:54 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.Core/Services/IFileService.cs
> +        public List<int> GetFilesCount(int userId, int directoryId, CancellationToken cancellationToken = default);
А почему это не асинхронно?

2021-06-13 21:55 UTC, AlexanderTsvirkun commented on EFPractice/EFPractice.DAL/FileContext.cs
> +            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=helloappdb;Trusted_Connection=True;");
Снова хардкодишь?
Буду по рукам бить

2021-06-13 21:55 UTC, AlexanderTsvirkun requested changes
Исправляй грубые ошибки

2021-06-18 19:28 UTC, Anvean21 commented
> Случайные коммиты

2021-07-23 15:36 UTC, merged