Js practice
Anvean21/KovalenkoEvgeniy-Homework pull request #21
Opened 2021-06-30 15:21 UTC by Anvean21

2021-07-06 08:48 UTC, DoludaSergey requested changes
все смешалось в общую кучу, очень долго и сложно искать нужные задания (практика скриптов, штмл и тд)все должно быть в разных ПР

2021-07-06 09:35 UTC, Anvean21 commented
> все смешалось в общую кучу, очень долго и сложно искать нужные задания (практика скриптов, штмл и тд)все должно быть в разных ПР

Да, знаю, я писал вам по поводу кривых ПРов из VS Code, ветки криво создавались, но проблему я уже зарезолвил.
Если нажать на название (имя) коммита, то он отобразиться отдельно от всех и можно будет легко и быстро всё посмотреть.

2021-07-08 07:19 UTC, DoludaSergey approved these changes

2021-07-08 07:20 UTC, merged

2021-07-08 07:54 UTC, DoludaSergey reviewed
ok