Asp.Net core mvс homework
Anvean21/KovalenkoEvgeniy-Homework pull request #24
Opened 2021-07-09 19:02 UTC by Anvean21

2021-07-10 18:24 UTC, vladimir-shirmanov requested changes
Недоделано, много мусора, не дочитал теорию и все возможности asp.net core

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/HomeController.cs
> +    public class HomeController : Controller
Ну по хорошему сгенереный шаблонный код лучше удалять

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +        AspCoreContext db;
решил вообще не заморачиваться? :), хотя бы внутри МВЦ проекта для приличия бы сервис создал

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +            if (db.Users.Any(x => x.Email == user.Email))
Так а где проверка паролей?

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +        [ValidateAntiForgeryToken]
А почему тут используешь этот атрибут а на пару строк выше в signup методе нет?

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +        private async Task Authenticate(string userName)
Асинхроные методы мы именуем с суфиксом Async вконце, исключение только  action контролера которые видит пользователь

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/FileLogger.cs
> +    public class FileLogger : ILogger
А это тебе зачем? В ASP.NET Core MVC есть такой класс встроенный по умолчанию, нужно просто настроить правильно appsettings.json

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Models/LoginModel.cs
> +        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,5}", ErrorMessage = "Некорректный адрес")]
В dataanotation есть специальный атрибут для валидации имейлов. Регулярками в данном случае уже почти никто не пользуется, они слишком тяжелые по ресурсам

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +            if (ModelState.IsValid)
Опять же выше почему то это забыл

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Startup.cs
> +                    context.Response.Headers.Add("X-Checked-By", $"{Configuration["lastName"]}");
Так задание было что бы этот хэдр добавлялся при ЛЮБОМ запросе на сайт. Чувствуешь разницу с тем что требовалось и с тем что сделал ты?

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Startup.cs
> +                endpoints.MapGet("/hello.json", async context =>
Так а где остальные задания? Например с редиректом? недоделано

2021-07-10 18:24 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/logger.txt
> +Now listening on: https://localhost:5001
Надо было добавить логирование Exception-ов а не всего подряд. Это неправильно

2021-07-11 10:51 UTC, Anvean21 commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +            if (db.Users.Any(x => x.Email == user.Email))
> Так а где проверка паролей?

Конферм паролей/емейлов сделан с помощью аннотаций.

2021-07-11 10:52 UTC, Anvean21 commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +        [ValidateAntiForgeryToken]
> А почему тут используешь этот атрибут а на пару строк выше в signup методе нет?

В методе Get этот атрибут не нужен

2021-07-11 10:54 UTC, Anvean21 commented on AspCorePractice/AspCorePractice/Models/LoginModel.cs
> +        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,5}", ErrorMessage = "Некорректный адрес")]
> В dataanotation есть специальный атрибут для валидации имейлов. Регулярками в данном случае уже почти никто не пользуется, они слишком тяжелые по ресурсам

Да, там используется аттрибут для мыла, в ТЗ написано что "Email должен соответствовать по паттерну", поэтому заюзал и регулярку.

2021-07-11 11:40 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +            if (db.Users.Any(x => x.Email == user.Email))
Так интересно. Ну возьми через постмен отправь сюда запрос и посмотри что получится

2021-07-11 11:41 UTC, vladimir-shirmanov commented on AspCorePractice/AspCorePractice/Controllers/UserController.cs
> +        [ValidateAntiForgeryToken]
В методе пост signup. Внимательнее читай комменты и код пиши

2021-07-11 18:58 UTC, Anvean21 commented on AspCorePractice/AspCorePractice/Startup.cs
> +                endpoints.MapGet("/hello.json", async context =>
> Так а где остальные задания? Например с редиректом? недоделано

Пропустил его видимо, уже доделал.

2021-07-11 18:59 UTC, Anvean21 commented on AspCorePractice/AspCorePractice/Startup.cs
> +                    context.Response.Headers.Add("X-Checked-By", $"{Configuration["lastName"]}");
> Так задание было что бы этот хэдр добавлялся при ЛЮБОМ запросе на сайт. Чувствуешь разницу с тем что требовалось и с тем что сделал ты?

Чувствую сенсей, пофикшено:)

2021-07-11 19:05 UTC, Anvean21 commented
> Недоделано, много мусора, не дочитал теорию и все возможности asp.net core

Комменты пофикшены, мусор почищен, теория дочитана, финал Евро пропущен ))

2021-07-23 15:35 UTC, merged